import React, { createContext, useContext, useState } from "react";

export type Language = "tr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  tr: {
    // Nav
    "nav.shift": "Vardiya",
    "nav.transactions": "Satışlar",
    "nav.reports": "Raporlar",
    "nav.station": "İstasyon",
    "nav.settings": "Ayarlar",
    "nav.tagline": "Akaryakıt İstasyonları İçin Dijital Operasyon Platformu",
    "nav.system_panel": "Sistem Paneli",
    "nav.manager_panel": "Müdür Paneli",
    "nav.users": "Kullanıcılar",

    // Header & Meta
    "header.title": "Vardiya Mutabakatı",
    "header.subtitle": "Tüm satış kanallarının tek ekranda özeti",
    "header.active_station": "İstasyon",
    "header.select_station": "İstasyon Seçin",
    "header.all_stations": "Tüm İstasyonlar",
    "header.shift_time": "06:00 - 14:00",
    "header.new_shift": "Yeni Vardiya Başlat",
    "header.close_shift": "Vardiyayı Kapat & Sıfırla",
    "header.add_sale": "Satış Ekle",
    "header.refresh": "Yenile",

    // Worker Cards
    "worker.title": "İşçi",
    "worker.liters": "Satılan Litre",
    "worker.cash": "Nakit Satış",
    "worker.pos": "POS (Kart)",
    "worker.fast": "FAST",
    "worker.total_label": "Toplam Satışlar",
    "worker.total_sub": "aktif işçinin toplamı",
    "worker.add_fuel": "Dolum / Fiş",
    "worker.pos_sim": "Sanal POS",
    "worker.qr_sim": "QR / FAST",
    "worker.close": "Vardiyayı Kapat",

    // Summary Totals
    "summary.opening_cash": "Açılış Kasası",
    "summary.opening_sub": "Vardiya başında kasaya konulan nakit",
    "summary.cash_sales": "Toplam Nakit Satış",
    "summary.cash_sub": "Vardiya içinde yapılan nakit satış",
    "summary.pos_sales": "Toplam POS (Kart)",
    "summary.pos_sub": "Vardiya içinde yapılan kart satış",
    "summary.fast_sales": "Toplam FAST",
    "summary.fast_sub": "Vardiya içinde yapılan FAST satış",
    "summary.liters_total": "Toplam Satılan Litre",
    "summary.liters_sub": "Vardiya toplam akaryakıt satışı",
    "summary.expected_cash": "Beklenen Kasa",
    "summary.total_revenue": "Toplam Satış Tutarı",
    "summary.general_total": "Genel Toplam",
    "summary.general_sub": "Vardiya satışlarının toplam tutarı",

    // Reconciliation Status
    "status.completed_title": "Vardiya Mutabakatı Tamamlandı",
    "status.completed_desc": "Açılış kasası ve tüm satış kanalları başarıyla eşleştirildi.",
    "status.active_title": "Canlı Vardiya Açık & Devam Ediyor",
    "status.active_desc": "Saha personellerinden canlı satış ve tahsilat verisi alınıyor.",
    "status.shortage": "Kasa Açığı Tespit Edildi",
    "status.surplus": "Kasa Fazlası Tespit Edildi",
    "status.no_active": "Şu Anda Açık Vardiya Bulunmuyor",
    "status.no_active_sub": "Satışları takip etmek ve kasa mutabakatı yapmak için yeni bir vardiya başlatın.",

    // Product Breakdown
    "product.title": "Ürün Bazlı Detay",
    "product.optional": "(Opsiyonel)",
    "product.desc": "Ana ekranda ürün ayrımı olmadan çalışır. Detaylı analiz için ürün bazlı veriler görüntülenebilir.",
    "product.toggle": "Ürün Bazlı Detayı Göster",
    "product.table_title": "ÜRÜN BAZLI SATIŞ DETAYI",
    "product.col_product": "Ürün",
    "product.col_liters": "Satılan Litre",
    "product.col_cash": "Nakit Satış (TL)",
    "product.col_pos": "POS (Kart) (TL)",
    "product.col_fast": "FAST (TL)",
    "product.col_total": "Toplam Tutar (TL)",
    "product.benzin": "Kurşunsuz 95 (Benzin)",
    "product.motorin": "Motorin (Dizel)",
    "product.lpg": "Otogaz (LPG)",
    "product.chart_title": "Satılan Litre Dağılımı",
    "product.chart_total": "Toplam",
    "product.info_note": "Ürün bazlı detay, ana mutabakat işlemini etkilemez. Sistem, ana ekranda toplam litre ve toplam tutarlar üzerinden çalışır. Ürün bazlı veriler analiz ve raporlama için kullanılır.",

    // Transactions Page
    "tx.breadcrumb": "OPERASYON",
    "tx.sub_breadcrumb": "SATIŞ DEFTERİ",
    "tx.title": "Satış ve İşlem Kayıtları",
    "tx.subtitle": "Akaryakıt pompaları ve istasyondan yapılan gerçek zamanlı işlem akışı",
    "tx.new_record": "Yeni Satış Kaydı",
    "tx.card_total_rev": "TOPLAM CİRO HACMİ",
    "tx.card_total_liters": "TOPLAM YAKIT LİTRESİ",
    "tx.card_cash_pos": "NAKİT / POS DAĞILIMI",
    "tx.card_credit": "VERESİYE ALACAKLAR",
    "tx.col_time": "İŞLEM SAATİ",
    "tx.col_type": "TÜR",
    "tx.col_product": "ÜRÜN / YAKIT TÜRÜ",
    "tx.col_amount_liters": "MİKTAR (LİTRE)",
    "tx.col_total": "TUTAR",
    "tx.col_channel": "ÖDEME KANALI",
    "tx.col_note": "AÇIKLAMA / PLAKA",
    "tx.fuel": "Akaryakıt",
    "tx.market": "Market",
    "tx.other": "Diğer",
    "tx.cash": "Nakit",
    "tx.pos": "POS / Kart",
    "tx.fast": "EFT / FAST",
    "tx.credit": "Veresiye",
    "tx.no_records": "Henüz işlem kaydı bulunmuyor.",

    // Stations Page
    "st.title": "İstasyon Yönetimi",
    "st.subtitle": "İstasyon seçin veya yeni istasyon ekleyin",
    "st.add_pump": "Pompa Ekle",
    "st.new_station": "Yeni İstasyon",
    "st.card_revenue": "Toplam Satış Tutarı",
    "st.card_revenue_sub": "Bugünkü açık vardiya cirosu",
    "st.card_liters": "Toplam Verilen Litre",
    "st.card_liters_sub": "Pompalanan toplam yakıt",
    "st.card_vehicles": "Hizmet Verilen Araç",
    "st.card_vehicles_sub": "İstasyona giriş yapan araç sayısı",
    "st.pumps_title": "İstasyon Pompaları",
    "st.pumps_defined": "Pompa Tanımlı",
    "st.duty": "Görevli",
    "st.no_duty": "Vardiya Yok",
    "st.active": "Aktif",
    "st.idle": "Boşta",
    "st.workers_title": "İşçi & Vardiya Satışları",
    "st.active_workers": "Aktif Çalışan Personel",
    "st.live_stream": "Canlı Akış",
    "st.no_shifts": "Bu istasyonda şu anda açık bir vardiya bulunmuyor.",
    "st.no_shifts_sub": "Yeni bir işçi ve pompa vardiyası başlatmak için sol menüden Vardiya sekmesine gidin.",
    "st.col_fuel_type": "Yakıt Türü",
    "st.col_liters": "Verilen Litre",
    "st.col_revenue": "Satış Tutarı",
    "st.col_vehicles": "Araç Sayısı",
    "st.no_sales_yet": "Henüz bu vardiyada satış kaydı bulunmuyor.",
    "st.vehicles_count": "Araç",

    // Reports Page
    "reports.title": "Geçmiş Vardiya Raporları",
    "reports.subtitle": "Dün, geçen hafta veya geçmiş tarihlerdeki tüm mutabakat karneleri",
    "reports.filter_period": "Zaman Aralığı",
    "reports.today": "Bugün",
    "reports.yesterday": "Dün",
    "reports.last_7": "Son 7 Gün",
    "reports.this_month": "Bu Ay",
    "reports.all": "Tüm Zamanlar",
    "reports.col_date": "Tarih & Saat",
    "reports.col_station": "İstasyon",
    "reports.col_cashier": "Kasiyer / İşçiler",
    "reports.col_expected": "Beklenen Kasa",
    "reports.col_closing": "Fiziki Kapanış",
    "reports.col_difference": "Kasa Farkı",
    "reports.col_status": "Mutabakat Durumu",
    "reports.matched": "Tam Mutabakat (0,00 TL)",
    "reports.no_data": "Seçilen tarih aralığında geçmiş mutabakat kaydı bulunamadı.",

    // Settings Page
    "settings.title": "Sistem ve Tercihler",
    "settings.subtitle": "FuelOS operasyonel parametreler, kasa toleransı ve kullanıcı tercihleri",
    "settings.user_info": "Kullanıcı ve Oturum Bilgileri",
    "settings.full_name": "Ad Soyad",
    "settings.email": "E-posta",
    "settings.role": "Yetki Rolü",
    "settings.appearance": "Görünüm ve Sistem Dili",
    "settings.lang_label": "Arayüz Dili",
    "settings.lang_sub": "Türkçe veya İngilizce dil seçimi",
    "settings.theme_label": "Tema Modu",
    "settings.theme_sub": "Koyu veya aydınlık görünüm",
    "settings.dark_mode": "Koyu Mod",
    "settings.light_mode": "Açık Mod",
    "settings.tolerance_title": "Kasa Mutabakat Tolerans Limiti (DEC-001 / K-001)",
    "settings.tolerance_sub": "Vardiya kapanışında kabul edilebilir kuruş / bozuk para yuvarlama payı",
    "settings.tolerance_saved": "Kaydedildi",
    "settings.quick_select": "Hızlı Tolerans Seçimi",
    "settings.zero_tol": "Sıfır Tolerans",
    "settings.default_tol": "Varsayılan",
    "settings.mid_tol": "Orta Esneklik",
    "settings.high_tol": "Genişletilmiş",
    "settings.custom_tol": "Özel Tolerans Tutarı (₺)",
    "settings.save": "Kaydet",
    "settings.how_it_works": "Nasıl Çalışır?",
    "settings.how_it_works_desc": "Akaryakıt istasyonlarında bozuk para (kuruş) bulunamaması nedeniyle gerçekleşen küçük yuvarlama farkları kasayı yapay olarak 'Açık' veya 'Fazla' göstermemelidir.",
    "settings.matched_desc": "Fark bu limiti aştığında vardiya otomatikman Kasa Açığı (Shortage) veya Kasa Fazlası (Surplus) statüsüne geçer.",
    "settings.manager_only": "* Tolerans limiti sadece Şirket Yöneticisi ve İstasyon Müdürü tarafından güncellenebilir.",

    // Roles
    "role.super_admin": "Süper Yönetici",
    "role.station_manager": "İstasyon Müdürü",
    "role.cashier": "Kasiyer",

    // Shifts Page
    "shifts.title": "Akıllı Vardiya Mutabakatı",
    "shifts.subtitle": "Açılış nakdi, vardiya içi nakit satışlar, kapanış kasası ve otomatik kasa farkı tespiti",
    "shifts.breadcrumb_op": "Operasyon",
    "shifts.breadcrumb_sub": "Vardiya & Mutabakat",
    "shifts.filter_all": "Tüm Vardiyalar",
    "shifts.filter_open": "Sadece Açık Olanlar",
    "shifts.filter_closed": "Kapatılan Vardiyalar",
    "shifts.formula_title": "Akıllı Kasa Doğrulama Formülü:",
    "shifts.formula_desc": "Beklenen Kasa = Açılış Nakdi + Vardiya İçi Nakit Satışlar. Sistem kapanışta sayılan tutarı otomatik karşılaştırır.",
    "shifts.col_station_user": "İstasyon & Personel",
    "shifts.col_time": "Vardiya Zamanı",
    "shifts.col_opening": "Açılış Kasa",
    "shifts.col_cash_sales": "Nakit Satışlar",
    "shifts.col_expected": "Beklenen Kasa",
    "shifts.col_closing": "Fiziki Kapanış",
    "shifts.col_status": "Kasa Mutabakat Durumu",
    "shifts.col_action": "Aksiyon",
    "shifts.close_btn": "Kapat",
    "shifts.open_tag": "Açık Oturum",
    "shifts.shortage_tag": "KASA AÇIĞI",
    "shifts.surplus_tag": "Kasa Fazlası",
    "shifts.no_records": "Filtrelere uygun kayıtlı bir vardiya bulunamadı.",
    "shifts.start_prefix": "Başlangıç:",
    "shifts.end_prefix": "Bitiş:",
    "shifts.in_progress": "Devam Ediyor",

    // Modals
    "modal.open_shift_title": "Yeni Vardiya Başlat",
    "modal.step1": "Adım 1: İstasyon, Süre & Kasa",
    "modal.step2": "Adım 2: Personel & Avatar Bilgisi",
    "modal.station_select": "İstasyon Seçimi *",
    "modal.pump_assign": "Pompa / Saha Ataması",
    "modal.free_worker": "Tüm İstasyon / Serbest Saha Personeli",
    "modal.shift_duration": "Vardiya Süresi & Otomatik Kapanış",
    "modal.manual_close": "Manuel Kapanış",
    "modal.manual_close_desc": "Kapatma butonuna basıldığında kapanır",
    "modal.hours_8": "8 Saatlik Vardiya",
    "modal.hours_12": "12 Saatlik Vardiya",
    "modal.custom_hours": "Özel Kapanış Saati",
    "modal.auto_close_note": "Süre dolduğunda vardiya otomatik kapanır",
    "modal.advance_cash": "Personele Verilen Bozuk Para Avansı (TL)",
    "modal.advance_cash_hint": "Zorunlu değil, personelin yanında bulunan açılış avansı.",
    "modal.next_step": "İleri: Personel Bilgisi",
    "modal.back_step": "Geri",
    "modal.worker_name": "Personel / Pompa Görevlisi Adı *",
    "modal.worker_name_ph": "Örn: Ahmet Yılmaz",
    "modal.avatar_photo": "Fotoğraf / Avatar Seçimi",
    "modal.avatar_male": "Erkek",
    "modal.avatar_female": "Kadın",
    "modal.avatar_custom_photo": "Özel Foto",
    "modal.avatar_none": "İsimsiz",
    "modal.start_shift_btn": "Vardiyayı Başlat",

    "modal.close_title": "Vardiyayı Kapat & Kilitle",
    "modal.close_sub": "Fiziki kasa teslimi ve mutabakat hesabı",
    "modal.closing_cash_label": "Kapanış Kasa Nakit Tutarı (TL) *",
    "modal.closing_cash_hint": "Kasada fiilen sayılan nakit para. Sistem bu tutarı otomatik olarak satışlarla karşılaştıracaktır.",
    "modal.closing_notes": "Kapanış / Devir Notu (Opsiyonel)",
    "modal.closing_notes_ph": "Örn: 200 TL bozuk para madeni para torbasında bırakıldı.",
    "modal.close_and_reconcile": "Vardiyayı Kapat & Mutabakat Yap",

    "modal.add_sale_title": "Yeni Akaryakıt Satış & Pompa Fişi",
    "modal.add_sale_sub": "Akaryakıt pompalarından yapılan anlık satış kaydı",
    "modal.select_staff_rfid": "Vardiyadaki Personel (RFID / Kart)",
    "modal.select_pump": "Dolum Yapılan Pompa",
    "modal.fuel_type": "Akaryakıt Türü",
    "modal.fuel_amount": "Satış Tutarı (₺)",
    "modal.fuel_liters": "Verilen Miktar (Litre)",
    "modal.payment_channel": "Ödeme Yöntemi",
    "modal.payment_cash": "Nakit (Elden Tahsilat)",
    "modal.payment_pos": "POS / Kredi Kartı",
    "modal.payment_fast": "EFT / FAST / Havale",
    "modal.plate_number": "Araç Plakası (Opsiyonel)",
    "modal.plate_ph": "34 ABC 123",
    "modal.save_sale": "Satışı Kaydet",

    // Station Modals & Extra
    "st.add_pump_modal_title": "Pompa Ekle",
    "st.pump_number": "Pompa Numarası",
    "st.pump_label": "Pompa Etiketi *",
    "st.supported_fuels": "Desteklenen Yakıt Türleri (virgülle ayırın)",
    "st.station_name": "İstasyon Adı *",
    "st.station_code": "İstasyon Kodu *",
    "st.city": "Şehir *",
    "st.district": "İlçe",
    "st.general_shift": "Genel Vardiya",
    "st.empty_pumps": "Henüz tanımlı pompa bulunmuyor.",
    "st.empty_pumps_btn": "İlk pompayı ekleyin",

    // Modals & General
    "common.cancel": "Vazgeç",
    "common.confirm": "Onayla",
    "common.save": "Kaydet",
    "common.close": "Kapat",
    "common.loading": "Yükleniyor...",
    "common.logout": "Çıkış Yap",
  },

  en: {
    // Nav
    "nav.shift": "Shift",
    "nav.transactions": "Sales",
    "nav.reports": "Reports",
    "nav.station": "Station",
    "nav.settings": "Settings",
    "nav.tagline": "Digital Operations Platform for Fuel Stations",
    "nav.system_panel": "System Admin",
    "nav.manager_panel": "Manager View",
    "nav.users": "Users",

    // Header & Meta
    "header.title": "Shift Reconciliation",
    "header.subtitle": "Single-screen overview of all sales channels",
    "header.active_station": "Station",
    "header.select_station": "Select Station",
    "header.all_stations": "All Stations",
    "header.shift_time": "06:00 - 14:00",
    "header.new_shift": "Start New Shift",
    "header.close_shift": "Close & Reset Shift",
    "header.add_sale": "Add Sale",
    "header.refresh": "Refresh",

    // Worker Cards
    "worker.title": "Worker",
    "worker.liters": "Dispensed Liters",
    "worker.cash": "Cash Sales",
    "worker.pos": "POS (Card)",
    "worker.fast": "FAST / Wire",
    "worker.total_label": "Total Sales",
    "worker.total_sub": "combined across active workers",
    "worker.add_fuel": "Dispense / Receipt",
    "worker.pos_sim": "Virtual POS",
    "worker.qr_sim": "QR / FAST",
    "worker.close": "Close Shift",

    // Summary Totals
    "summary.opening_cash": "Opening Cash",
    "summary.opening_sub": "Cash placed into register at shift start",
    "summary.cash_sales": "Total Cash Sales",
    "summary.cash_sub": "Cash sales collected during shift",
    "summary.pos_sales": "Total POS (Card)",
    "summary.pos_sub": "Card payments collected during shift",
    "summary.fast_sales": "Total FAST",
    "summary.fast_sub": "Instant transfer payments during shift",
    "summary.liters_total": "Total Liters Sold",
    "summary.liters_sub": "Total dispensed fuel volume in shift",
    "summary.expected_cash": "Expected Cash",
    "summary.total_revenue": "Total Revenue",
    "summary.general_total": "Grand Total",
    "summary.general_sub": "Total sum of shift sales across channels",

    // Reconciliation Status
    "status.completed_title": "Shift Reconciliation Completed",
    "status.completed_desc": "Opening cash and all sales channels successfully balanced.",
    "status.active_title": "Active Live Shift In Progress",
    "status.active_desc": "Real-time sales and collection data streaming from forecourt staff.",
    "status.shortage": "Cash Shortage Detected",
    "status.surplus": "Cash Surplus Detected",
    "status.no_active": "No Active Shift Currently Open",
    "status.no_active_sub": "Start a new shift above to initialize worker reconciliation and begin tracking live pump sales.",

    // Product Breakdown
    "product.title": "Product Breakdown",
    "product.optional": "(Optional)",
    "product.desc": "Operates without product distinction on main view. Enable for in-depth product analytics.",
    "product.toggle": "Show Product Breakdown",
    "product.table_title": "SALES BREAKDOWN BY PRODUCT",
    "product.col_product": "Product",
    "product.col_liters": "Liters Sold",
    "product.col_cash": "Cash Sales (TL)",
    "product.col_pos": "POS (Card) (TL)",
    "product.col_fast": "FAST (TL)",
    "product.col_total": "Total Amount (TL)",
    "product.benzin": "Gasoline 95",
    "product.motorin": "Diesel",
    "product.lpg": "Autogas (LPG)",
    "product.chart_title": "Dispensed Volume Share",
    "product.chart_total": "Total",
    "product.info_note": "Product breakdown does not alter the core cash reconciliation. The system balances on aggregate volumes and total collections. Product data is used for analytics and historical reporting.",

    // Transactions Page
    "tx.breadcrumb": "OPERATIONS",
    "tx.sub_breadcrumb": "SALES LEDGER",
    "tx.title": "Sales & Transaction Records",
    "tx.subtitle": "Real-time feed of pump dispensations and station payments",
    "tx.new_record": "New Sale Entry",
    "tx.card_total_rev": "TOTAL REVENUE VOLUME",
    "tx.card_total_liters": "TOTAL FUEL DISPENSED",
    "tx.card_cash_pos": "CASH / POS SPLIT",
    "tx.card_credit": "CREDIT RECEIVABLES",
    "tx.col_time": "TIMESTAMP",
    "tx.col_type": "TYPE",
    "tx.col_product": "PRODUCT / FUEL",
    "tx.col_amount_liters": "VOLUME (LITERS)",
    "tx.col_total": "AMOUNT",
    "tx.col_channel": "PAYMENT CHANNEL",
    "tx.col_note": "NOTE / PLATE",
    "tx.fuel": "Fuel",
    "tx.market": "Convenience",
    "tx.other": "Other",
    "tx.cash": "Cash",
    "tx.pos": "POS / Card",
    "tx.fast": "EFT / FAST",
    "tx.credit": "Credit",
    "tx.no_records": "No transaction records found.",

    // Stations Page
    "st.title": "Station Management",
    "st.subtitle": "Select a station or add a new location",
    "st.add_pump": "Add Pump",
    "st.new_station": "New Station",
    "st.card_revenue": "Total Sales Revenue",
    "st.card_revenue_sub": "Active shift revenue today",
    "st.card_liters": "Total Liters Dispensed",
    "st.card_liters_sub": "Total pumped fuel volume",
    "st.card_vehicles": "Vehicles Served",
    "st.card_vehicles_sub": "Total vehicles visited station",
    "st.pumps_title": "Station Pumps",
    "st.pumps_defined": "Pumps Configured",
    "st.duty": "Assigned",
    "st.no_duty": "No Shift",
    "st.active": "Active",
    "st.idle": "Idle",
    "st.workers_title": "Worker & Shift Sales",
    "st.active_workers": "Active Staff on Duty",
    "st.live_stream": "Live Feed",
    "st.no_shifts": "No active shifts open at this station.",
    "st.no_shifts_sub": "Go to Shift dashboard to start a new worker shift.",
    "st.col_fuel_type": "Fuel Type",
    "st.col_liters": "Liters Dispensed",
    "st.col_revenue": "Total Revenue",
    "st.col_vehicles": "Vehicles",
    "st.no_sales_yet": "No sales recorded in this shift yet.",
    "st.vehicles_count": "Vehicles",

    // Reports Page
    "reports.title": "Historical Shift Reports",
    "reports.subtitle": "Audit shift reconciliations from yesterday, last week or prior months",
    "reports.filter_period": "Time Period",
    "reports.today": "Today",
    "reports.yesterday": "Yesterday",
    "reports.last_7": "Last 7 Days",
    "reports.this_month": "This Month",
    "reports.all": "All Time",
    "reports.col_date": "Date & Time",
    "reports.col_station": "Station",
    "reports.col_cashier": "Cashier / Staff",
    "reports.col_expected": "Expected Cash",
    "reports.col_closing": "Counted Cash",
    "reports.col_difference": "Cash Variance",
    "reports.col_status": "Reconciliation Status",
    "reports.matched": "Balanced (0.00 TL)",
    "reports.no_data": "No historical shift records found for the selected period.",

    // Settings Page
    "settings.title": "System & Preferences",
    "settings.subtitle": "FuelOS operational parameters, cash tolerance and user settings",
    "settings.user_info": "User & Session Profile",
    "settings.full_name": "Full Name",
    "settings.email": "Email Address",
    "settings.role": "Access Role",
    "settings.appearance": "Appearance & Language",
    "settings.lang_label": "System Language",
    "settings.lang_sub": "Select interface language (TR/EN)",
    "settings.theme_label": "Theme Mode",
    "settings.theme_sub": "Toggle dark or light theme",
    "settings.dark_mode": "Dark Mode",
    "settings.light_mode": "Light Mode",
    "settings.tolerance_title": "Cash Reconciliation Tolerance Limit (DEC-001 / K-001)",
    "settings.tolerance_sub": "Allowable coin rounding variance threshold at shift close",
    "settings.tolerance_saved": "Saved",
    "settings.quick_select": "Quick Threshold Presets",
    "settings.zero_tol": "Zero Tolerance",
    "settings.default_tol": "Default",
    "settings.mid_tol": "Moderate",
    "settings.high_tol": "Extended",
    "settings.custom_tol": "Custom Tolerance Amount (₺)",
    "settings.save": "Save Changes",
    "settings.how_it_works": "How It Works?",
    "settings.how_it_works_desc": "In fuel forecourts, fractional change discrepancies due to coin scarcity should not artificially flag shifts as Shortage or Surplus.",
    "settings.matched_desc": "If the physical cash variance is within this threshold, the shift is validated as Matched / Balanced.",
    "settings.manager_only": "* Tolerance limit can only be modified by Company Admin and Station Manager.",

    // Roles
    "role.super_admin": "Super Admin",
    "role.station_manager": "Station Manager",
    "role.cashier": "Cashier",

    // Shifts Page
    "shifts.title": "Smart Shift Reconciliation",
    "shifts.subtitle": "Opening cash, forecourt cash sales, counted closing cash and automatic variance reconciliation",
    "shifts.breadcrumb_op": "Operations",
    "shifts.breadcrumb_sub": "Shift & Reconciliation",
    "shifts.filter_all": "All Shifts",
    "shifts.filter_open": "Active Shifts Only",
    "shifts.filter_closed": "Closed Shifts",
    "shifts.formula_title": "Smart Cash Verification Formula:",
    "shifts.formula_desc": "Expected Cash = Opening Cash + Shift Cash Sales. System automatically reconciles counted cash against expected cash upon closing.",
    "shifts.col_station_user": "Station & Staff",
    "shifts.col_time": "Shift Timing",
    "shifts.col_opening": "Opening Cash",
    "shifts.col_cash_sales": "Cash Sales",
    "shifts.col_expected": "Expected Cash",
    "shifts.col_closing": "Physical Closing",
    "shifts.col_status": "Reconciliation Status",
    "shifts.col_action": "Action",
    "shifts.close_btn": "Close",
    "shifts.open_tag": "Active Shift",
    "shifts.shortage_tag": "SHORTAGE",
    "shifts.surplus_tag": "Surplus",
    "shifts.no_records": "No shift records found matching the filters.",
    "shifts.start_prefix": "Start:",
    "shifts.end_prefix": "End:",
    "shifts.in_progress": "In Progress",

    // Modals
    "modal.open_shift_title": "Start New Shift",
    "modal.step1": "Step 1: Station, Duration & Float",
    "modal.step2": "Step 2: Attendant Profile & Avatar",
    "modal.station_select": "Select Station *",
    "modal.pump_assign": "Pump / Forecourt Assignment",
    "modal.free_worker": "Entire Station / Roaming Forecourt Staff",
    "modal.shift_duration": "Shift Duration & Auto-Close",
    "modal.manual_close": "Manual Close",
    "modal.manual_close_desc": "Remains active until manually closed by manager",
    "modal.hours_8": "8-Hour Shift",
    "modal.hours_12": "12-Hour Shift",
    "modal.custom_hours": "Custom Close Time",
    "modal.auto_close_note": "Shift automatically locks when timer expires",
    "modal.advance_cash": "Staff Change / Float Advance (TL)",
    "modal.advance_cash_hint": "Optional, enter if change float is issued to staff at shift start.",
    "modal.next_step": "Next: Staff Profile",
    "modal.back_step": "Back",
    "modal.worker_name": "Staff / Attendant Name *",
    "modal.worker_name_ph": "e.g. John Doe",
    "modal.avatar_photo": "Photo / Avatar Selection",
    "modal.avatar_male": "Male",
    "modal.avatar_female": "Female",
    "modal.avatar_custom_photo": "Custom Photo",
    "modal.avatar_none": "Anonymous",
    "modal.start_shift_btn": "Start Shift",

    "modal.close_title": "Close & Lock Shift",
    "modal.close_sub": "Physical cash handover & reconciliation audit",
    "modal.closing_cash_label": "Closing Cash Count (TL) *",
    "modal.closing_cash_hint": "Actual cash counted in register. The system automatically compares this with registered sales.",
    "modal.closing_notes": "Handover / Closing Notes (Optional)",
    "modal.closing_notes_ph": "e.g. 200 TL coins left in cash pouch for next shift.",
    "modal.close_and_reconcile": "Close Shift & Reconcile",

    "modal.add_sale_title": "New Fuel Sale & Pump Receipt",
    "modal.add_sale_sub": "Instant sales entry simulating pump automation",
    "modal.select_staff_rfid": "Staff on Shift (RFID / Card)",
    "modal.select_pump": "Dispensing Pump",
    "modal.fuel_type": "Fuel Grade",
    "modal.fuel_amount": "Total Amount (₺)",
    "modal.fuel_liters": "Dispensed Volume (Liters)",
    "modal.payment_channel": "Payment Method",
    "modal.payment_cash": "Cash (In Hand)",
    "modal.payment_pos": "POS / Card",
    "modal.payment_fast": "EFT / FAST / Wire",
    "modal.plate_number": "Vehicle Plate (Optional)",
    "modal.plate_ph": "34 ABC 123",
    "modal.save_sale": "Save Transaction",

    // Station Modals & Extra
    "st.add_pump_modal_title": "Add Pump",
    "st.pump_number": "Pump Number",
    "st.pump_label": "Pump Label *",
    "st.supported_fuels": "Supported Fuel Grades (comma separated)",
    "st.station_name": "Station Name *",
    "st.station_code": "Station Code *",
    "st.city": "City *",
    "st.district": "District",
    "st.general_shift": "General Shift",
    "st.empty_pumps": "No pumps configured yet.",
    "st.empty_pumps_btn": "Add the first pump",

    // Modals & General
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.save": "Save",
    "common.close": "Close",
    "common.loading": "Loading...",
    "common.logout": "Log Out",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("fuelos_lang") as Language | null;
    return saved === "en" || saved === "tr" ? saved : "tr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("fuelos_lang", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
